apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  destination:
    namespace: example-app
    server: https://kubernetes.default.svc
  project: example-project
  source:
    path: sample-app/
    repoURL: https://github.com/torstenbrink/argo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
